-- District Seeding for Tamil Nadu
-- Total 38 Districts

INSERT INTO `districts` (`id`, `name`) VALUES
(1, 'Ariyalur'),
(2, 'Chengalpattu'),
(3, 'Chennai'),
(4, 'Coimbatore'),
(5, 'Cuddalore'),
(6, 'Dharmapuri'),
(7, 'Dindigul'),
(8, 'Erode'),
(9, 'Kallakurichi'),
(10, 'Kanchipuram'),
(11, 'Kanyakumari'),
(12, 'Karur'),
(13, 'Krishnagiri'),
(14, 'Madurai'),
(15, 'Mayiladuthurai'),
(16, 'Nagapattinam'),
(17, 'Namakkal'),
(18, 'Nilgiris'),
(19, 'Perambalur'),
(20, 'Pudukkottai'),
(21, 'Ramanathapuram'),
(22, 'Ranipet'),
(23, 'Salem'),
(24, 'Sivaganga'),
(25, 'Tenkasi'),
(26, 'Thanjavur'),
(27, 'Theni'),
(28, 'Thoothukudi'),
(29, 'Tiruchirappalli'),
(30, 'Tirunelveli'),
(31, 'Tirupathur'),
(32, 'Tiruppur'),
(33, 'Tiruvallur'),
(34, 'Tiruvannamalai'),
(35, 'Tiruvarur'),
(36, 'Vellore'),
(37, 'Viluppuram'),
(38, 'Virudhunagar')
ON DUPLICATE KEY UPDATE name = VALUES(name);
